### PR TITLE
fixed journal & snapshot queries

### PR DESCRIPTION
**Pull request by andreabalducci**
Added missing ordering & limit.
I think testkit should check for query correctness (but is slow & needs lot of data or requires an api change).

Journal & Shapshots id should be of type ObjectId rather than a concatenated strings (haven't touched).

### CODE REVIEW

**Comment by Silv3rcircl3** [comment]
@andreabalducci [there](https://github.com/akkadotnet/Akka.Persistence.MongoDB/blob/dev/src/Akka.Persistence.MongoDb/MongoDbExtension.cs#L58) are descending idexes for the SequenceNr so I'm not sure if it makes a difference. Furthermore the current implementation is outdated and we need to update this to Akka 1.0.7 which introduced a persistence update, that's also the reason why the build failed. 
Would you maybe like to do that? I'm currently working mostly on Akka.Streams and therefore I'm running out of time...

**Comment by andreabalducci** [comment]
@Silv3rcircl3 makes the difference, without an index on the query mongo picks the $natural index on mmap (don't know on other mongo storage engine). Having an index does not guarantee it's picked up on query without a sort order (or an hint)

I'll do the update to 1.0.7.

**Comment by Silv3rcircl3** [comment]
@andreabalducci great, thank you very much. I will close this PR and you can include the changes in the 1.0.7 version.

**Comment by andreabalducci** [comment]
@Silv3rcircl3 there's any documentation about new persistence and how is supposed to work?
Have to find how to use Context & AtomicWrite, btw looks very similar to NEventStore Commit (disclaimer, I'm the maintainer of NEventStore)

**Comment by Danthar** [comment]
The sqllite implementation in the core akka.net repo can be used as a reference.

-----Original Message-----

**Comment by Silv3rcircl3** [comment]
@andreabalducci If there are still question about the implementation details you could also ask @cconstantin in the gitter chat, he has updated the persistence layer from the jvm

**Pull request closed without merging**
