### PR TITLE
Persistence implementation for MongoDB

### PR DESCRIPTION
**Pull request by Silv3rcircl3**

### CODE REVIEW

**Comment by Horusiath** [comment]
It's good :+1:  :) . My only note - could you remove the proto-buf stuff (examples and definitions) from the PR? They are unnecessary.

**Comment by Silv3rcircl3** [comment]
Of course, also the licenses and the changes.txt?

**Comment by Horusiath** [comment]
I think so. Changes from external dependencies are not needed in source code, while it looks like having license file is not part of proto-buf license contract with library users (Akka.Remote and Akka.Persistence use it as well).

**Comment by Silv3rcircl3** [comment]
Done. Never used proto so I was not if these stuff is necessary :smirk:

**Comment by garethbudden** [comment]
Hi, I've not much experience with Akka yet but have a few years with MongoDb.  So purely from the mongo side of things here's the suggestions I'd have...

Secondary indexes.
I couldn't see anywhere that defines any secondary indexes for the journal and snapshot collection, so presently searches will do collection scans.  Maybe it could define the index in the code or just mention it in the readme?

ClassMappings
It looks like you're using the AutoMap feature in the mongo driver, I've used that myself but one day someone "accidentally" alters a property name and suddenly the documents aren't hydrating the classes properly.  The simplest way to fix this is with the mongo mapping attributes.  Then if someone wants to specify their own they can do ```BsonClassMap.RegisterClassMap<......``` which will overwrite your settings.

Like I say I'm very new to Akka so it's probably worth checking with @Horusiath before paying too much attention to me :smile:

**Comment by Silv3rcircl3** [comment]
Great suggestions, thx! 
I never needed indexing but it was on my todo list, unfortunately I wasn't motivated enough to read the docs :wink:

I will implement both suggestions today or tomorrow and post the code here so that you both can have a look before I update the PR.

**Comment by Aaronontheweb** [comment]
setting up CI for this sucker tonight - got MongoDB installed on my persistence image. I'll put the connection information up on an issue here once I get the image configured properly.

**Comment by Silv3rcircl3** [comment]
@garethbudden 
I'm creating a index per possible filter parameter, is this the correct approach?

For the journal
> JournalCollection.Indexes.CreateOneAsync(Builders<JournalEntry>.IndexKeys.Ascending(entry => entry.PersistenceId));  

>JournalCollection.Indexes.CreateOneAsync(Builders<JournalEntry>.IndexKeys.Ascending(entry => entry.SequenceNr));

and for the snapshots
>SnapshotCollection.Indexes.CreateOneAsync(Builders<SnapshotEntry>.IndexKeys.Ascending(entry => entry.PersistenceId));  
>SnapshotCollection.Indexes.CreateOneAsync(Builders<SnapshotEntry>.IndexKeys.Ascending(entry => entry.SequenceNr));  
>SnapshotCollection.Indexes.CreateOneAsync(Builders<SnapshotEntry>.IndexKeys.Ascending(entry => entry.Timestamp));

**Comment by garethbudden** [comment]
I think for the journal collection a compound index may work...

> { PersistenceId:1,SequenceNr:-1 }

This allows for searching on just PersistenceId or PersistenceId and SequenceNr.  
The snapshot looks trickier, it looks like you can search on PersistenceId and then either SequenceNr, Timestamp, or both!  It may be worth filling a collection with data, creating the various index options, and then running the queries that the code can produce with explain(), something like this...

> db.journal.find({$and:[{PersistenceId :"abc"},{SequenceNr:{$gte:2}},{SequenceNr:{$lte:4}}]}).explain()

That should help guide you to the best performing indexes, hope this helps?

**Comment by Silv3rcircl3** [comment]
I filled the snapshotstore with 1 persistenceId and 100000 snapshots and used the following queries
>db.SnapshotStore.find({ "PersistenceId" : "$b", "SequenceNr" : { "$gte" : 200, "$lte" : 500 }})  
>db.SnapshotStore.find({ "PersistenceId" : "$b", "Timestamp" : { "$gte" : 635709169795127153,"$lte" : 635709169796057153 } })  
>db.SnapshotStore.find({ "PersistenceId" : "$b", "SequenceNr" : { "$gte" : 200, "$lte" : 500 }, "Timestamp" : { "$gte" : 635709169795127153,"$lte" : 635709169796057153 } })

##### Only PersistenceId as Index for all three queries
- 100000 documents scanned
- ~ 150 milliseconds

##### PersistenceId and SequenceNr as Index
Query 1 & 3
- 301 documents scanned
- ~ 1 millisecond  

of course the values will increase for query 3 if the range from sequencenr is higher  

Query 2
- 100000 documents scanned
- ~ 193 milliseconds

##### PersistenceId, SequenceNr and Timestamp as index
Query 1
- 301 documents scanned
- ~ 1 millisecond  

Query 2
- 100000 documents scanned
- ~ 210 milliseconds

Query 3
- 299 documents scanned
- ~ 1 millisecond

So I think we need to know which combinations of parameters are possible, if for example the timestamp is only used with the sequencenr as filter, I would use the last index.
If otherwise the timestamp is only used for edge cases with a small sequencenr range, I would use the second index... 
@Horusiath could you give us some advice here ? :)

**Comment by Horusiath** [comment]
The most important part of each query is PersistenceId - it's always used to separate the events/snapshots we care about in each query. PersistenceId is always compared for equality and is applied to each query (both for journal and snapshot store).

Second is the SequenceNr used to narrow the number of events to be received. It's used in two scenarios:

1. Range (from-to) query
2. Get the highest sequence number in PersistenceId scope

Timestamps are usually used in reverse order (starting from the latest ones), but... as they are part of snapshots, they are not as performance intensive as journal. Usually you need to query only for the single, latest snapshot in actor's PersistenceId scope. And since it's practically always used with PersistenceId and SequenceNr, I wouldn't care about it so much.

**Pull request merged**
